[package]
name = "f2q"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.1"
rand = "0.8.5"
rayon = "1.8.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

[profile.release]
lto = "fat"
